### ISSUE TITLE
Calling a function with structs leads to wrong code at -O2

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#10]
Taken from `gcc.c-torture/execute/20000603-1.c`, fails at -O2 and higher:

```
$ cat 20000603-1.c 
#include <stdlib.h>
#include <stdio.h>

struct s1 { double d; };
struct s2 { double d; };
union u { struct s1 x; struct s2 y; };

double f(struct s1 *a, struct s2 *b)
{
  a->d = 1.0;
  return b->d + 1.0;
}

int main()
{
  union u a;
  a.x.d = 0.0;
  printf("%g\n", f (&a.x, &a.y));
  if (f (&a.x, &a.y) != 2.0)
    abort ();
  return 0;
}
$ ./bin/gcc 20000603-1.c -O1 && ./a.out
2
$ ./bin/gcc 20000603-1.c -O2 && ./a.out
1
```

**Comment by fxcoudert** [comment]
diff between the generated assembly at -O1 and -O2 (commenting out the printf statement):

```
--- O1.s	2020-08-31 11:38:20.000000000 +0200
+++ O2.s	2020-08-31 11:38:44.000000000 +0200
@@ -1,19 +1,21 @@
 	.arch armv8-a
 	.text
 	.align	2
+	.p2align 4,,11
 	.globl _f
 _f:
 LFB9:
 	.cfi_startproc
+	ldr	d1, [x1]
 	fmov	d0, 1.0e+0
 	str	d0, [x0]
-	ldr	d1, [x1]
 	fadd	d0, d1, d0
 	ret
 	.cfi_endproc
 LFE9:
 	.section __TEXT,__text_startup,regular,pure_instructions
 	.align	2
+	.p2align 4,,11
 	.globl _main
 _main:
 LFB10:
@@ -23,13 +25,13 @@ LFB10:
 	.cfi_offset 29, -32
 	.cfi_offset 30, -24
 	mov	x29, sp
+	add	x1, sp, 24
+	mov	x0, x1
 	str	xzr, [sp, 24]
-	add	x0, sp, 24
-	mov	x1, x0
 	bl	_f
 	fmov	d1, 2.0e+0
 	fcmp	d0, d1
-	bne	L5
+	bne	L6
 	mov	w0, 0
 	ldp	x29, x30, [sp], 32
 	.cfi_remember_state
@@ -37,7 +39,7 @@ LFB10:
 	.cfi_restore 29
 	.cfi_def_cfa_offset 0
 	ret
-L5:
+L6:
 	.cfi_restore_state
 	bl	_abort
 	.cfi_endproc
```

**Comment by iains** [comment]
> diff between the generated assembly at -O1 and -O2 (commenting out the printf statement):
> 
> ```
> --- O1.s	2020-08-31 11:38:20.000000000 +0200
> +++ O2.s	2020-08-31 11:38:44.000000000 +0200
> @@ -1,19 +1,21 @@
>  	.arch armv8-a
>  	.text
>  	.align	2
> +	.p2align 4,,11
>  	.globl _f
>  _f:
>  LFB9:
>  	.cfi_startproc
> +	ldr	d1, [x1]
>  	fmov	d0, 1.0e+0
>  	str	d0, [x0]
> -	ldr	d1, [x1]
this is a NOP, it seems
>  	fadd	d0, d1, d0
>  	ret
>  	.cfi_endproc
>  LFE9:
>  	.section __TEXT,__text_startup,regular,pure_instructions
>  	.align	2
> +	.p2align 4,,11
not important,  to correctness,  only to performance
>  	.globl _main
>  _main:
>  LFB10:
> @@ -23,13 +25,13 @@ LFB10:
>  	.cfi_offset 29, -32
>  	.cfi_offset 30, -24
>  	mov	x29, sp
> +	add	x1, sp, 24
> +	mov	x0, x1
x1 = x0 = sp + 24
>  	str	xzr, [sp, 24]
> -	add	x0, sp, 24
> -	mov	x1, x0
x1 = x0 = sp +24
>  	bl	_f
>  	fmov	d1, 2.0e+0
>  	fcmp	d0, d1
> -	bne	L5
> +	bne	L6
diference only in the label name.
>  	mov	w0, 0
>  	ldp	x29, x30, [sp], 32
>  	.cfi_remember_state
> @@ -37,7 +39,7 @@ LFB10:
>  	.cfi_restore 29
>  	.cfi_def_cfa_offset 0
>  	ret
> -L5:
> +L6:
>  	.cfi_restore_state
>  	bl	_abort
>  	.cfi_endproc
> ```

The two codes seem to be equivalent - so not sure what's happening - does it still abort with the printf commented?
(I would be less surprised to find that printf was messing things up - problems with variadic funcs are expected).

**Comment by iains** [comment]
> > diff between the generated assembly at -O1 and -O2 (commenting out the printf statement):
> > ```
> > --- O1.s	2020-08-31 11:38:20.000000000 +0200
> > +++ O2.s	2020-08-31 11:38:44.000000000 +0200
> > @@ -1,19 +1,21 @@
> >  	.arch armv8-a
> >  	.text
> >  	.align	2
> > +	.p2align 4,,11
> >  	.globl _f
> >  _f:
> >  LFB9:
> >  	.cfi_startproc
> > +	ldr	d1, [x1]
> >  	fmov	d0, 1.0e+0
> >  	str	d0, [x0]
> > -	ldr	d1, [x1]
> > ```
> 
> this is a NOP, it seems

*NO* it isn't - *X0 aliases X1*, I wonder what this does on aarch64-linux?

**Comment by fxcoudert** [comment]
I can make it fail without printf, in a test case guaranteed with 0% variadic functions:

```
$ cat a.c
struct s1 { double d; };
struct s2 { double d; };
union u { struct s1 x; struct s2 y; };

double f(struct s1 *a, struct s2 *b)
{
  a->d = 1.0;
  return b->d + 1.0;
}

int main()
{
  union u a;
  a.x.d = 0.0;
  return (f (&a.x, &a.y) != 2.0) ? 1 : 0;
}
$ ./bin/gcc a.c -O1 && ./a.out ; echo $?
0
$ ./bin/gcc a.c -O2 && ./a.out ; echo $?
1
```

**Comment by iains** [comment]
see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96875
(this is not an issue specific to the darwin variant)

**Comment by iains** [comment]
there doesn't seem to be any reason to keep this open here - if we need to XFAIL the test case, to avoid the noise, then that can be done.
