### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. 

### ISSUE THREAD

**Issue by dianekim0410** [iains/gcc-darwin-arm64#106]
I tried to create an environment using the following `ch` command
`ch create csci104 --image usccsci104/docker:20.04 --shell /bin/bash --volume "/Users/username/Documents/csci104:/work" --security-opt seccomp:unconfined --cap-add SYS_PTRACE --privileged --replace`

but I am getting the following error. 

`Cannot create new environment. Error from Dockerfile build:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

When I manually tried to build a docker using `docker build -t myimage .`, it seems to work.
Any advice? Thanks.

**Comment by iains** [comment]
From your description, I cannot see how this is related to the Arm64 port of GCC?

**Comment by iains** [comment]
closing as unrelated to the arm64 port.
