### ISSUE TITLE
CLT 15 betas: some failures with ld, ld-classic is OK

### ISSUE THREAD

**Issue by simonjwright** [iains/gcc-darwin-arm64#124]
We were all pleased when the link failures with CLT 15.0 (e.g. issue #117), which could be worked round with `-Wl,-ld_classic`, no longer needed the workround with 15.1beta, and 15.1beta2.

The Ada tool suite contains some sizeable Ada tools. Built on aarch64 with GCC 13.1.0 and CLT 14.2 or 3, it has run for several months.

On rebuilding one of the tools (`alr`), still with GCC 13.1.0 but with CLT 15.1b2, it failed at runtime (incorrect internal count).

While investigating, I found that another tool (`gprconfig`) failed to catch an exception which it should have done, and that the executables had changed size.

It took me a lot longer than it should have done to suspect the linker, and it turns out that both errors are fixed by linking using `ld-classic`.

@fxcoudert are you seeing this anywhere else?
(I will not be able to do much for the next week or two because of WG21 commitments, that includes testing any newer XC versions that need access to my CI machines9

**Comment by iains** [comment]
apologies, I mean to reply to the comment not edit it ... blame jet lag.

**Comment by fxcoudert** [comment]
@simonjwright do you have a minimal reproducer? For someone who knows nothing about Ada

**Comment by simonjwright** [comment]
I have no idea how I managed to convince myself that this was ld vs ld-classic. I’ve been unable to reproduce the uncaught exception, and the problem with alr turned out to be an upstream bug (return statement doesn’t return the value updated in the statement). It’ll be a battle to create a reproducer.
