### ISSUE TITLE
Gm2 compilation fails 

### ISSUE THREAD

**Issue by Occipt** [iains/gcc-darwin-arm64#128]
Greetings.

I just took a fresh pull.  Gcc/g++ build without incident on my M1 Mini.  When I add gm2 to the mix, the gm2 compiler builds but has a problem compiling the gm2 library:

/bin/sh ../libtool --tag=CC   \
                   --mode=compile /Users/build/opt/gcc/bld/gm2-arm/./gcc/gm2 -B/Users/build/opt/gcc/bld/gm2-arm/./gcc/
[...]
../../../../../src/gcc-darwin-arm64/libgm2/libm2pim/../../gcc/m2/gm2-libs/NumberIO.mod: In function 'm2pim_NumberIO_HexToStr':
../../../../../src/gcc-darwin-arm64/libgm2/libm2pim/../../gcc/m2/gm2-libs/NumberIO.mod:237:1: error: label '.L873' in the middle of basic block 3
  237 | BEGIN
      | ^~~~~
during GIMPLE pass: vect
../../../../../src/gcc-darwin-arm64/libgm2/libm2pim/../../gcc/m2/gm2-libs/NumberIO.mod:237:1: internal compiler error: verify_flow_info failed

Previous gm2 builds succeeded without incident.  It is not clear whether this is in your balliwick.

Thank you for the port.

Sincerely,
Occipt

**Comment by iains** [comment]
this is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113750 which is fixed (there are some other fixes for vector issues also).  I will be updating the branch in a few days to include all of these fixes.

**Comment by iains** [comment]
the latest rebase (https://github.com/iains/gcc-darwin-arm64/commit/8eaa8e78badd7e1d8c2873a2565d95bf9859eb3f) includes the fix for this and for a number of vector-related issues.
