### ISSUE TITLE
Internal compiler error on optimization

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#13]
Reduced from `gcc.dg/autopar/reduc-8.c`:

```
$ cat reduc-8.c      
void testmax (const char *c)
{
  char accum = 0;
  int i;

  for (i = 0; i < 3200; i++) {
    accum += c[i];
  }
}

int __attribute__((optimize ("-ftree-parallelize-loops=0")))
main (void)
{ 
  static char C[3200] = { 0xff };
  testmax (C);
}
$ ./bin/gcc reduc-8.c
$ ./bin/gcc reduc-8.c -O
reduc-8.c:16:1: internal compiler error: Segmentation fault: 11
   16 | }
      | ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

The backtrace for the ICE is not very helpful, I'm afraid:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x00000001011bb6a0 cc1`output_object_blocks() at varasm.c:7682:35
    frame #2: 0x0000000100de7750 cc1`::compile_file() at toplev.c:515:28
    frame #3: 0x000000010139ce2c cc1`toplev::main(int, std::__va_list*) at toplev.c:2314:24
    frame #4: 0x000000010139cb08 cc1`toplev::main(this=0x000000016fdff8f8, argc=<unavailable>, argv=<unavailable>)
    frame #5: 0x000000010139e77c cc1`main(argc=18, argv=0x000000016fdff938) at main.c:39:22
    frame #6: 0x00000001d29e8a04 libdyld.dylib`start + 4
```

**Comment by iains** [comment]
OK, so this is something to do with section anchors.  Unfortunately, section anchors don't play nicely with the ld64/Mach-O atom model:

* ld64 thinks it is free to split things on any linker-visible symbol, but section anchors work on the basis of a block of stuff that's stuck together with a starting symbol and then a series of smaller offsets ... splitting that up will crash.

* traditionally, 0-sized objects have been allowed in ELF semantics, this messes with the atom model too.

I *did* make section anchors work for PowerPC Darwin, a long time ago - but it was a bit messy and I'm not sure how much it was used.   So ..... my initial inclination is to look for a way to switch this off - or to make sure it's limited to cases that won't upset ld64.

**Comment by iains** [comment]
"fixed" (i.e. disabled) by the commit mentioned.
