### ISSUE TITLE
clang 16 called as `as` does not accept stdin input anymore

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#136]
Heads-up about an Apple bug, found in testing Xcode 16 / clang 16.

```
[fx@mini-m2:/tmp] % as toto.s                                                  
[fx@mini-m2:/tmp] % cat toto.s | as
clang: error: no input files
```

This used to work, but doesn't anymore. As a consequence, `gcc -pipe` does not work anymore:

```
[fx@mini-m2:/tmp] 1 % cat a.c
int main (void) { return 0; }
[fx@mini-m2:/tmp] % gcc-14 a.c
[fx@mini-m2:/tmp] % gcc-14 a.c -pipe
clang: error: no input files
```

----

I have reported this to Apple as **FB15021557**. Content of the report below:

```
Take a small assembly source file below (a.s). You can compile it with `as a.s`. But passing the source as stdin, with `cat a.s | as`, used to work with all previous versions of as/clang. It does not anymore. This is a regression, and is triggered by GCC when compiling with the -pipe option.

% cat a.s
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 15, 0	sdk_version 15, 0
	.globl	_main                           ; -- Begin function main
	.p2align	2
_main:                                  ; @main
	.cfi_startproc
; %bb.0:
	sub	sp, sp, #16
	.cfi_def_cfa_offset 16
	mov	w0, #0                          ; =0x0
	str	wzr, [sp, #12]
	add	sp, sp, #16
	ret
	.cfi_endproc
                                        ; -- End function
.subsections_via_symbols
% as a.s
% cat a.s | as
clang: error: no input files
```

**Comment by fxcoudert** [comment]
`as` has been replaced by a shell script:

```
$ file /Library/Developer/CommandLineTools/usr/bin/as
/Library/Developer/CommandLineTools/usr/bin/as: Paul Falstad's zsh script text executable, ASCII text
$ cat /Library/Developer/CommandLineTools/usr/bin/as
#!/bin/zsh

DIR="$(dirname "$(realpath "$0")")"

# remove -q and -Q args (which clang does not support)
for arg do
  shift
  [ "$arg" = "-q" ] && continue
  [ "$arg" = "-Q" ] && continue
  set -- "$@" "$arg"
done

# use clang driver to run clang's integrated assembler
$DIR/clang -x assembler -c "$@"


```

----

Work-around suggested:

```
cat toto.s | clang -x assembler -c -
```

_“We see `as` as deprecated. Probably not going to 'fix' this.”_

**Comment by markmentovai** [comment]
@iains

This is causing [MacPorts bug 70641](https://trac.macports.org/ticket/70641), because MacPorts uses `-pipe` by default (…/etc/macports/macports.conf configurepipe).

Xcode 16 `as` can be made to read from standard input by giving it `-` instead of an input path. GCC has support for this, if configured with the `AS_NEEDS_DASH_FOR_PIPED_INPUT` macro defined.

I’m working locally with https://github.com/macports/macports-ports/compare/master...markmentovai:macports-ports:gcc14_xcode16, which does the trick for me. I’m now looking at this in a non-MacPorts GCC build.

**Comment by iains** [comment]
All: i've been OOO and away from email - so catching up.

I'd prefer a single solution that works across the supported range but we can also drive this from configure test if needed.

Hopefully, will have a chance to look over next weekend.

**Comment by markmentovai** [comment]
https://github.com/iains/gcc-darwin-arm64/issues/136#issuecomment-2356628102:
> I'd prefer a single solution that works across the supported range but we can also drive this from configure test if needed.

Xcode 15 (and previous) `as` also understands `-` meaning to read from standard input, although it doesn’t require it. binutils `gas` should similarly tolerate, but not require, the `-`. I think that `AS_NEEDS_DASH_FOR_PIPED_INPUT` could be unconditionally applied everywhere.

**Comment by iains** [comment]
that will be what I try - my guess would be that the possible issue would be with earlier toolchains that use cctools as.  However, a configure test is not too hard to arrange .. and is in some ways more future-proof.

**Comment by markmentovai** [comment]
cctools `as` understands the `-` too. I think you’ll be hard-pressed to find an `as` that doesn’t.

[Xcode 15.3 cctools as/driver.c `main`](https://github.com/apple-oss-distributions/cctools/blob/0ab07c0b798167e296a347c1dd961e70d8e3b1bd/as/driver.c#L83):

```c
		/*
		 * Treat a single "-" as reading from stdin input also.
		 */
```

**Comment by saagarjha** [comment]
I filed FB14314277 for this too back in July. I see a handful of dupes for it so maybe they'll actually fix it?

**Comment by fxcoudert** [comment]
> I see a handful of dupes for it so maybe they'll actually fix it?

Private conversation indicates that they see `as` as deprecated, and are probably not going to fix this.

**Comment by iains** [comment]
I'm going with the AS_NEEDS_DASH_FOR_PIPED_INPUT - please be patient - $dayjob is busy ... (hopefully I'll commit to trunk this weekend and then add to the darwin branches)

**Comment by iains** [comment]
> > I see a handful of dupes for it so maybe they'll actually fix it?
> 
> Private conversation indicates that they see `as` as deprecated, and are probably not going to fix this.

clearly, we can do our own thing - I have a wrapper-driver for the LLVM backend that mimics the cctools-like interface (so we would not need to maintain the assembler - just the wrapper).  Prefer not to have more things  to maintain - but it can also simplify rolling our changes ...

**Comment by iains** [comment]
FAOD - having an "integrated assembler" in GCC is a thought-of idea - - but it's (very) non-trivial to arrange, so do not hold your breath on that happening (we'd still need to source the assembler code from LLVM anyway since binutils does not have sufficient Mach-O support).

**Comment by fxcoudert** [comment]
> MacPorts uses -pipe by default

Homebrew was as well, but I think it's mostly for historical reasons, and we've now switched it off.

**Comment by iains** [comment]
> > MacPorts uses -pipe by default
> 
> Homebrew was as well, but I think it's mostly for historical reasons, and we've now switched it off.

AFAIU, at some stage, it was faster (since it means that the .s file need not be written).  However, with an effective buffer-cache it might well be completely moot now.

(someone should do at least a rough benchmark to see if there is still merit).

====

In any case, we need to make it work - since there are undoubtedly Makefiles and other stuff out there that depend on it.

**Comment by iains** [comment]
actually, now I think some more and page in some dusty memories;  this was also a workaround for an assembler/debug bug (but I do not recall what bug and when it might have been fixed).

**Comment by iains** [comment]
BTW : macports folks - now we have DCO, there is no requirement to make a (c) assignment to submit a patch to GCC, so feel free to do so - please CC me if it's Darwin-specific because I can OK those.

It would also be helpful to have Bugzilla reports for generic problems (i.e. this one is totally not specific to the arm64 branch) .. .

**Comment by markmentovai** [comment]
GCC bug filed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116794.

**Comment by cooljeanius** [comment]
> GCC bug filed: [gcc.gnu.org/bugzilla/show_bug.cgi?id=116794](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116794).

This is now fixed.

**Comment by iains** [comment]
> > GCC bug filed: [gcc.gnu.org/bugzilla/show_bug.cgi?id=116794](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116794).
> 
> This is now fixed.

but only so far on trunk, I will back port when there's some test cycles spare.

**Comment by cooljeanius** [comment]
> > > GCC bug filed: [gcc.gnu.org/bugzilla/show_bug.cgi?id=116794](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116794).
> > 
> > 
> > This is now fixed.
> 
> but only so far on trunk, I will back port when there's some test cycles spare.

OK, I reopened it, then.

**Comment by iains** [comment]
this is not specific to arm64 - so let's track it in GCC Bugzilla with the filed bug.
