### ISSUE TITLE
Invalid assembly generated at -O3

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#15]
Invalid assembly generated at `-O3`:

```
$ cat sound.c 
void toto (char audio[8192]) {
  int i;

  for (i = 0; i < 4095; i++)
    audio[i] = i / 8;
}
$ ./bin/gcc sound.c -c -O2
$ ./bin/gcc sound.c -c -O3
/var/folders/5b/7mrgq6j55b51p7ztj1r3gv400000gq/T//ccPBI4WH.s:36:14: error: immediate must be an integer in range [0, 255].
        movi    v0.8b, 0xfffffffffffffffe
                       ^
```

Reduced from `gcc.c-torture/compile/sound.c`
Diff of the generated assembly:

```
--- O2.s	2020-08-31 13:58:03.000000000 +0200
+++ O3.s	2020-08-31 13:58:12.000000000 +0200
@@ -6,16 +6,48 @@
 _toto:
 LFB0:
 	.cfi_startproc
-	mov	x1, 0
+	adrp	x1, lC0@GOTPAGE
+	add	x1, x1, lC0@PAGEOFF;momd
+	movi	v17.4s, 0x10
+	add	x2, x0, 4080
+	movi	v16.4s, 0x4
+	movi	v7.4s, 0x8
+	movi	v6.4s, 0xc
+	ldr	q2, [x1]
+	mov	x1, x0
 	.p2align 3,,7
 L2:
-	asr	w2, w1, 3
-	strb	w2, [x0, x1]
-	add	x1, x1, 1
-	cmp	x1, 4095
+	mov	v0.16b, v2.16b
+	add	v2.4s, v2.4s, v17.4s
+	add	v5.4s, v0.4s, v16.4s
+	add	v3.4s, v0.4s, v6.4s
+	add	v4.4s, v0.4s, v7.4s
+	xtn	v1.4h, v0.4s
+	xtn2	v1.8h, v5.4s
+	xtn	v0.4h, v4.4s
+	xtn2	v0.8h, v3.4s
+	ushr	v1.8h, v1.8h, 3
+	ushr	v0.8h, v0.8h, 3
+	xtn	v3.8b, v1.8h
+	xtn2	v3.16b, v0.8h
+	str	q3, [x1], 16
+	cmp	x2, x1
 	bne	L2
+	movi	v0.8b, 0xfffffffffffffffe
+	mov	w1, -1
+	str	w1, [x0, 4088]
+	strh	w1, [x0, 4092]
+	strb	w1, [x0, 4094]
+	str	d0, [x0, 4080]
 	ret
 	.cfi_endproc
 LFE0:
+	.const
+	.align	4
+lC0:
+	.word	0
+	.word	1
+	.word	2
+	.word	3
 	.ident	"GCC: (GNU) 11.0.0 20200829 (experimental)"
 	.subsections_via_symbols
```

**Comment by iains** [comment]
> Invalid assembly generated at `-O3`:
> 
> ```
> $ cat sound.c 
> void toto (char audio[8192]) {
>   int i;
> 
>   for (i = 0; i < 4095; i++)
>     audio[i] = i / 8;
> }
> $ ./bin/gcc sound.c -c -O2
> $ ./bin/gcc sound.c -c -O3
> /var/folders/5b/7mrgq6j55b51p7ztj1r3gv400000gq/T//ccPBI4WH.s:36:14: error: immediate must be an integer in range [0, 255].
>         movi    v0.8b, 0xfffffffffffffffe
>                        ^
> ```

I think there are a few instances of this in the test suite fails.  I wonder if it's because Darwin's char is signed (where many platforms [most?] are unsigned) - so perhaps a masking operation is missing?, dunno, just speculating.

**Comment by fxcoudert** [comment]
Not sure I get what you mean, but changing the `char` to `unsigned char` (or `signed char`) in the source does not fix the issue.

**Comment by iains** [comment]
i / 8 is signed

if looks like the output has done something like / equivalent to...

printf ... %d ... (int) ((char) i / 8)

what happens if you do
    audio[i] = (unsigned char) i / 8; 

?

**Comment by fxcoudert** [comment]
If `i` is made `unsigned char`, or cast to that type as you showed, then the error goes away.

**Comment by iains** [comment]
should be fixed by 
https://github.com/iains/gcc-darwin-arm64/commit/efda199974f514bfca7e5923eba1ee767820a611
