### ISSUE TITLE
The GCC PCH implementation depends on no-PIE

### ISSUE THREAD

**Issue by iains** [iains/gcc-darwin-arm64#2]
The static linker (ld64) declines -no_pie for arm64 arch.

This means that PCH is unusable at present since the GCC implementation relies on the being able to re-load data to the same address for multiple compiler invocations.

Not sure if this is a technical or a policy constraint (if, perhaps, this can be relaxed - at least for the desktop platform variant) - but reimplementing PCH is non-trivial task.

**Comment by iains** [comment]
> The static linker (ld64) declines -no_pie for arm64 arch.
> 
> This means that PCH is unusable at present since the GCC implementation relies on the being able to re-load data to the same address for multiple compiler invocations.
> 
> Not sure if this is a technical or a policy constraint (if, perhaps, this can be relaxed - at least for the desktop platform variant) - but reimplementing PCH is non-trivial task.

It is policy - so we have a more tricky problem to solve, much tho we'd all like a better PCH implementation, that's a non-trivial undertaking.  Seeking other possible solutions.

In the meantime, I've patched the testsuite to skip the tests for this for now, since they are just noise in the output.

**Comment by iains** [comment]
This is an unsolvable issue with the current GCC PCH implementation.  I tried a workaround where the PCH memory was forced to the same address (using mmap features).  That was successful, but the PCH implementation makes stronger assumptions than that - including that function pointers can be captured - which means that the TEXT segment cannot move between invocations - and that is obv. incompatible with PIE.

So to implement PCH we need a new streamer/serialiser for the state at the end of compilation (phase #4, I guess).  There's some hope that the streamer being implemented for modules might be reusable, but that's totally out of scope for GCC-11.

**Comment by cooljeanius** [comment]
Is PCH even something that's going to be sticking around? ISTR some devs saying they wanted to rip it out...

**Comment by iains** [comment]
> Is PCH even something that's going to be sticking around? ISTR some devs saying they wanted to rip it out...

I suspect that the majority of the GCC devs dislike the current PCH implementation - it is tricky to deal with (essentially it preserves the compiler state at the point that parsing the relevant headers is complete).  Therefore, there's a desire to get rid of it.

PCH is a useful tool in header-heavy projects (which tend to be C++ .. but actually also includes Objective-C stuff)

Some probably feel that C++20 modules is a sufficient replacement - but that doesn't cover Objective-C uses.

My opinion (unsubstantiated by hacking) is that the mechanisms of C++20 modules (preserving an AST rather than a compiler state) could be extended to cover the other c-family languages - but no-one has stepped up to do this (and it isn't too high on my list for Darwin at present).

**Comment by iains** [comment]
Jakub Jelinek has drafted and posted a patch that allows PCH to work with PIE executables **providing** that the PCH can be loaded into a fixed VMA.  I have drafted a patch for Darwin that does the latter (and is reliable at least on 64bit platform versions - including aarch64).

So we have a pending solution to this - the patch series is in my latest branches.

**Comment by iains** [comment]
this has been resolved upstream by:
r12-5320-ge4641191287ca613529
r12-5759-g22a982409323feb203
r12-5768-gfe7c3ecff1f9c0520090

Other patches are in progress that would make it even more flexible, but these above are sufficient for aarch64-darwin.

**Comment by iains** [comment]
the remaining patches are :
r12-5855-g747380f47da
r12-5856-gbf15cd665e
r12-5857-g0d5db1dd65
(as noted they are not strictly necessary in the short-term but it would probably be safer to back port the complete set in case the current choices of VMA become unusable in future OS versions)
