### ISSUE TITLE
ICE on __builtin_aarch64_get_fpcr()

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#24]
I am pretty sure this is a regression. I was debugging the `ieee_6.f90` issue, which looks like `__builtin_aarch64_set_fpcr()` is not working, and I found this ICE on `__builtin_aarch64_get_fpcr()` — which goes away with optimization:

```
$ cat tutu.c 
#include <stdio.h>

int main (void) {
  unsigned fpcr;
  fpcr = __builtin_aarch64_get_fpcr();
  printf("fpcr = %x\n", fpcr);
}
$ ./bin/gfortran tutu.c -O2
$ ./bin/gfortran tutu.c -O1
$ ./bin/gfortran tutu.c -O0
tutu.c: In function ‘main’:
tutu.c:7:1: error: unrecognizable insn:
    7 | }
      | ^
(insn 5 2 6 2 (set (mem/c:SI (plus:DI (reg/f:DI 87 virtual-stack-vars)
                (const_int -4 [0xfffffffffffffffc])) [1 fpcr+0 S4 A32])
        (unspec_volatile:SI [
                (const_int 0 [0])
            ] UNSPECV_GET_FPCR)) "tutu.c":5:10 -1
     (nil))
during RTL pass: vregs
tutu.c:7:1: internal compiler error: in extract_insn, at recog.c:2294
```

**Comment by fxcoudert** [comment]
Even with optimization I think we're generating wrong code:

```
$ cat toto.c 
#include <stdio.h>

#define FE_INVALID	1
#define FE_DIVBYZERO	2
#define FE_OVERFLOW	4
#define FE_UNDERFLOW	8
#define FE_INEXACT	16
#define FE_ALL_EXCEPT (FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW | FE_INEXACT)
#define FE_EXCEPT_SHIFT	8

int main (void)
{
  unsigned fpcr;
  
  fpcr = __builtin_aarch64_get_fpcr();
  printf("fpcr = %x\n", fpcr);

  fpcr |= (FE_ALL_EXCEPT << FE_EXCEPT_SHIFT);
  printf("fpcr = %x\n", fpcr);
  __builtin_aarch64_set_fpcr(fpcr);

  fpcr = __builtin_aarch64_get_fpcr();
  printf("fpcr = %x\n", fpcr);
}
$ ./bin/gcc -O1 toto.c && ./a.out
fpcr = 0
fpcr = 1f00
fpcr = 0
```

We first get the FPCR. Then we modify it to trap all exceptions, doing the same thing as `feenableexcept()` in glibc source (https://github.com/bminor/glibc/blob/master/sysdeps/aarch64/fpu/feenablxcpt.c). Then we read it back, but the bits were not set correctly.

Or is it expected? The glibc source (https://github.com/bminor/glibc/blob/master/sysdeps/aarch64/fpu/feenablxcpt.c) has a comment saying:

```
      /* Trapping exceptions are optional in AArch64; the relevant enable
	 bits in FPCR are RES0 hence the absence of support can be detected
	 by reading back the FPCR and comparing with the required value.  */
```

Do we have documentation stating whether trapping exceptions is expected to work, or not work, for Apple Silicon? I couldn't find anything.

**Comment by iains** [comment]
In what way a regression?
- the same IEEE tests that fail today, failed on the first set of results I have from 20/09/02 (which is the day after you supplied the patch, admittedly - but that's the first set I kept :/ ).

I haven't seen any doc other than the stuff you pointed me at (which is more-or-less incorporated in the README.md).

I guess we can ask for clarification from the Apple folks.

**Comment by iains** [comment]
The ICE is present on unpatched aarch64-linux-gnu :

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96968

**Comment by fxcoudert** [comment]
> In what way a regression? 

You're right, not a regression. The test was always failing, but I somehow thought the ICE was new, otherwise I would have seen it in my own testing when preparing the patch. Except I probably compiled with optimization, so… not a regression, sorry.

**Comment by iains** [comment]
> > In what way a regression?
> 
> You're right, not a regression. 
The test was always failing, but I somehow thought the ICE was new, otherwise I would have seen it in my own testing when preparing the patch. 

The ICE might be new (but I don't have enough CPU cycles to bisect) ..  the odd thing is that the unoptimised ieee_6  test doesn't seem to ICE - but fails execution.  So the ICE could be a regression on trunk (but it's not the underlying issue for ieee_6.f90, it seems).

FAIL: gfortran.dg/ieee/ieee_6.f90   -O0  execution test

**Comment by fxcoudert** [comment]
Closing then… not specific to darwin
