### ISSUE TITLE
libbacktrace incorrectly detects target as pecoff

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#25]
During bootstrap, stage3 libbacktrace incorrectly thinks an executable is `pecoff` instead of `macho`:

```
../../ibin/libbacktrace/config.log:libbacktrace_cv_sys_filetype=pecoff
../../ibin/prev-libbacktrace/config.log:libbacktrace_cv_sys_filetype=macho
../../ibin/stage1-libbacktrace/config.log:libbacktrace_cv_sys_filetype=macho
```

The detection is done by running `libbacktrace/filetype.awk` on an object file. Somehow, some generated bits in the object file content are the same as the pecoff signature, and the awk script is not restricting its matching to the first bytes of the file.

Maybe the script should be changed to only check the signature in the first bytes. But maybe that's on purpose, and we could also fix the issue by putting the macho checks first, as they are more specific:

```
diff --git a/libbacktrace/filetype.awk b/libbacktrace/filetype.awk
index 14d91581f7e..5cc31a07f46 100644
--- a/libbacktrace/filetype.awk
+++ b/libbacktrace/filetype.awk
@@ -1,13 +1,13 @@
 # An awk script to determine the type of a file.
-/\177ELF\001/      { if (NR == 1) { print "elf32"; exit } }
-/\177ELF\002/      { if (NR == 1) { print "elf64"; exit } }
-/\114\001/         { if (NR == 1) { print "pecoff"; exit } }
-/\144\206/         { if (NR == 1) { print "pecoff"; exit } }
-/\001\337/         { if (NR == 1) { print "xcoff32"; exit } }
-/\001\367/         { if (NR == 1) { print "xcoff64"; exit } }
 /\376\355\372\316/ { if (NR == 1) { print "macho"; exit } }
 /\316\372\355\376/ { if (NR == 1) { print "macho"; exit } }
 /\376\355\372\317/ { if (NR == 1) { print "macho"; exit } }
 /\317\372\355\376/ { if (NR == 1) { print "macho"; exit } }
 /\312\376\272\276/ { if (NR == 1) { print "macho"; exit } }
 /\276\272\376\312/ { if (NR == 1) { print "macho"; exit } }
+/\177ELF\001/      { if (NR == 1) { print "elf32"; exit } }
+/\177ELF\002/      { if (NR == 1) { print "elf64"; exit } }
+/\114\001/         { if (NR == 1) { print "pecoff"; exit } }
+/\144\206/         { if (NR == 1) { print "pecoff"; exit } }
+/\001\337/         { if (NR == 1) { print "xcoff32"; exit } }
+/\001\367/         { if (NR == 1) { print "xcoff64"; exit } }
```

This bug also affects `libsanitizer`, which is using the same script.

**Comment by fxcoudert** [comment]
Reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96971

**Comment by iains** [comment]
Interesting - I wonder if this is affecting the master GCC too (since I have observed that we don't get a backtrace quite often from the build dirs).

I guess it should be in order of most specific by character count - 
ELF
MACHO
PE/XCoff  (the last two it's are to know which is more reliable order)

**Comment by iains** [comment]
my latest build on darwin16 gets it right.
It might also, conceivably be dependent on whether we're using BSD awk or GNU gawk (although, it's not clear why it should).

**Comment by fxcoudert** [comment]
There is a different preexisting issue on trunk on x86_64-apple-darwin anyway. I've filed it at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96973

**Comment by fxcoudert** [comment]
With the patch for aarch64 () and the generic patch for macho (proposed here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96973) (also proposed here: https://github.com/ianlancetaylor/libbacktrace/issues/52), I get good runtime backtraces on aarch64-apple-darwin20:

```
At line 4 of file a.f90
Fortran runtime error: Index '20' of dimension 1 of array 'i' above upper bound of 10

Error termination. Backtrace:
#0  0x10456ef53 in ???
#1  0x10456fbaf in ???
#2  0x10456ffef in ???
#3  0x10455bbe7 in foo_
	at /Users/fx/irun/a.f90:4
#4  0x10455ba77 in bar_
	at /Users/fx/irun/a.f90:8
#5  0x10455bc3f in test
	at /Users/fx/irun/a.f90:12
#6  0x10455bc7b in main
	at /Users/fx/irun/a.f90:13
```

**Comment by iains** [comment]
Great!

I think that the proposed patch might be incomplete - AFAIR, FAT headers are always bigendian - and there are other fields we're reading but not swapping (we're also promoting the size to 64b).  I need to double-check and post to the PR.

**Comment by fxcoudert** [comment]
This is also being triggered for backtraces of gcc itself (cc1, f951): https://github.com/ianlancetaylor/libbacktrace/pull/40
I am now applying this additional patch to macho, if you want it:

```
@@ -903,7 +896,7 @@ macho_add_dsym (struct backtrace_state *state, const char *filename,
             + basenamelen
             + dsymsuffixdirlen
             + basenamelen
-            + 1);
+            + 2);
   dsym = backtrace_alloc (state, dsymlen, error_callback, data);
   if (dsym == NULL)
     goto fail;
@@ -922,7 +915,7 @@ macho_add_dsym (struct backtrace_state *state, const char *filename,
 
   if (diralc != NULL)
     {
-      backtrace_free (state, diralc, dirnamelen, error_callback, data);
+      backtrace_free (state, diralc, dirnamelen + 1, error_callback, data);
       diralc = NULL;
     }
 
```

**Comment by iains** [comment]
if you want to do a collated pull RQ for the WIP branch ahead of upstream review - that's fine (I'm not sure if Ian wants to review mach-o local stuff or if he will leave it to me).

**Comment by fxcoudert** [comment]
Iain has merged upstream the 4 patches necessary:
- https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=651c61c3cef123d70ec3582d53b58526a8cadcf7
- https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=488e33339e6dea3262a11307592e9aad87a97c8d
- https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=181f877b6c0e365c940b117c306e7309e19ffd89
- https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=a8a7a97b4e62195f9f538bed37177af171e75b8b
