### ISSUE TITLE
IEEE exception trap masks status on A12Z

### ISSUE THREAD

**Issue by ThemosTsikas** [iains/gcc-darwin-arm64#28]
Hello, 

What is the situation with the FPCR bits described by  (from system's <fenv.h>)

enum {
    __fpcr_trap_invalid   = 0x00000100,
    __fpcr_trap_divbyzero = 0x00000200,
    __fpcr_trap_overflow  = 0x00000400,
    __fpcr_trap_underflow = 0x00000800,
    __fpcr_trap_inexact   = 0x00001000,
    __fpcr_trap_denormal  = 0x00008000,
    __fpcr_flush_to_zero  = 0x01000000,
};

It seems to me that only  __fpcr_flush_to_zero can be set and reset in the FPCR of the A12Z.

**Comment by iains** [comment]
I haven't got to this level of detail yet - there are still larger pieces to fix :)

However - to clarify, are you stating that:
 1/ the builtins are not working correctly (i.e. not setting/clearing the bits as expected) ... or 
 2/ that the chip (A12Z) [or the OS privilege level] does not support the user making the changes? 

( it's a TODO to check with Apple about what is supposed to be possible).

**Comment by ThemosTsikas** [comment]
In https://static.docs.arm.com/ddi0595/i/SysReg_xml_v87A-2020-09.pdf or https://developer.arm.com/docs/ddi0595/i/aarch64-system-registers/fpcr look for "exception trap enable". 

"If the implementation does not support this exception, this bit is RAZ/WI."  I think this is the case for the A12Z. It was the case for the Cortex A-73 in the Juno development board and the RaspberryPi 3. The Cavium2, on the other hand, had traps enabled.

So, the answer is both 1 + 2. Setting the FPCR with MSR instruction does not affect the FPCR bits IOE, DZE, OFE, UFE, IXE, IDE. It may be that this can be changed with some privileged instruction but it is unlikely.

**Comment by ThemosTsikas** [comment]
Consider a Fortran program

program halt
use ieee_exceptions
Integer :: a(merge(20,40,ieee_support_halting(ieee_invalid)))
print *,size(a)
end program

If some Apple Macs don't support halting and some do, we have a problem because programs compiled on one will not produce the same results compiled on another (and will differ when the same program is executed elsewhere). ieee_support_halting should perhaps be taken out of list in 10.1.11 Specification expression and 10.1.12 Constant expression. 

I would like to have been present at the meeting where this decision was made, wearing a W. Kahan T-shirt.

**Comment by iains** [comment]
there's nothing especially new about this dilemma - the mac range contains more and less capable machines; e.g. "pro" variants with AVX512 and those without.

I'd expect that there are ways around this ranging from brutal:
 * disable the facility in GCC until it's supported by all members of the platform..
 * have a configuration option to switch it off...

to more subtle: 
 * emulation of the process in soft form when the chip doesn't have it (could be expensive in time)
 * perhaps having multilibs for the chip variants

once we have some kind of statement about what's supposed to work on released Silicon [I don't personally know what is expected to be supported], we ought to be able to address this in a (more) user-friendly manner than having a random outcome depending on the platform variant.

**Comment by iains** [comment]
is there any reason to keep this open now?
the DTKs are withdrawn - so we should concentrate on M1/M1max.

**Comment by ThemosTsikas** [comment]
As you say, the DTK is history.
