### ISSUE TITLE
Does not support `-arch arm64`: "this compiler does not support arm64"

### ISSUE THREAD

**Issue by TonyWu20** [iains/gcc-darwin-arm64#35]
I have tried building the gcc-11 in this repo and gcc-10 backported by @fxcoudert on my Apple M1 Mac mini, and both of them have the same problem: passing `-arch arm64` will receive an error `this compiler does not support arm64`. Instead, `-march=native` is fine. This issue is very troublesome because cmake will always test the gcc with `-arch arm64` and fail. I could not find any relevant issue or solution on the internet, so I ask here for help.

**Comment by iains** [comment]
should be fixed (gcc-11 here) by

https://github.com/iains/gcc-darwin-arm64/commit/6be7a45e8ace6a06e80c135e6682b46230c7a884

.. let me know if not.

**Comment by fxcoudert** [comment]
and included in the gcc-10 backport https://github.com/fxcoudert/gcc/commit/6ae8fb9bc550592ce0a3f8744cbe6745445119e7

**Comment by TonyWu20** [comment]
> should be fixed (gcc-11 here) by
> 
> [6be7a45](https://github.com/iains/gcc-darwin-arm64/commit/6be7a45e8ace6a06e80c135e6682b46230c7a884)
> 
> .. let me know if not.

@iains The fix works. Thank you!
