### ISSUE TITLE
Build error on Apple m1

### ISSUE THREAD

**Issue by huwei1024** [iains/gcc-darwin-arm64#39]
configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+

Then I. run this script:
./configure --with-gmp=/opt/homebrew/Cellar/gmp/6.2.1

error again.

How can i build this on Apple m1?

**Comment by iains** [comment]
in-source builds are not supported by GCC

please see  https://gcc.gnu.org/install/

and the linked pages for information on how to build GCC from source.

Note you will need `GMP` and `MPFR` and `MPC` to be available for the configuration to succeed.
