### ISSUE TITLE
have gfortran accept m64 flag on arm

### ISSUE THREAD

**Issue by kencu** [iains/gcc-darwin-arm64#40]
A user [found this](https://trac.macports.org/ticket/62109):
```
configure:6759: /opt/local/bin/gfortran-mp-devel -c -pipe -Os -m64 -x f95 conftest.f90 >&5
gfortran-mp-devel: error: unrecognized command-line option '-m64'
```

There could potentially be a lot of scripts that are setting that flag. 

Would it be reasonable for the gfortran driver to eat that?

**Comment by iains** [comment]
I'll take a look

**Comment by iains** [comment]
fixed on this morning's push

Note that the aarch64 backend does not use "m32" or "m64" (but rather -mabi=) .. so the effect of 'm64' is the same as '-mabi=darwinpcs'.  Anyway, that's done.

-m32 will be rejected (but it is also rejected by Apple's clang for C)

**Comment by kencu** [comment]
Thanks, Iain! Update moved out to users in today's MacPorts' updates.
