### ISSUE TITLE
arvis-app-launcher-plugin cannot find some standard macOS apps by default

### ISSUE THREAD

**Issue by cheuk-cheng** [iains/gcc-darwin-arm64#47]
By default, typing "activity monitor" (with or without quotes) in Arvis search bar in macOS could not find the standard "Activity Monitor" app located inside /Applications/Utilities folder.  What was strange was the following default user-config entries for arvis-app-launcher-plugin shown inside Arvis Preference window.  I thought the "deep: 3" key/value would enable Arvis to find "Activity Monitor" app inside "/Applications/Utilities" folder.

object {2}
    applicationFolders {3}
        win32 [1]
        darwin [1]
            0: /Applications
        linux [5]
        deep: 3

**Comment by iains** [comment]
this does not appear to be related to the GCC compiler in any way,
