### ISSUE TITLE
note: expanded from macro 'RTL_CHECK2'

### ISSUE THREAD

**Issue by ilg-ul** [iains/gcc-darwin-arm64#56]
I am doing a full rebuild of my development environment (called [xPack Build Box](https://github.com/xpack/xpack-build-box) - XBB), and in the bootstrap run, which mainly builds GCC with system clang, I noticed lots of messages, warnings and notes.

It may very well be from an improper configuration, but, anyway, I don't remember seeing so many messages in other similar builds.

I attached the full build logs.

[native-gcc-11.2.0.zip](https://github.com/iains/gcc-darwin-arm64/files/7613209/native-gcc-11.2.0.zip)

Please let me know if you need temporaries for specific files.

**Comment by iains** [comment]
if this is a bootstrap of the home-brew branch - then probably you should report issues there first ....
... or please check if it repeats on my master branch, which is up to date with known fixes

(I simply do not have enough hours to investigate all possible issues on forks from the original code).

**Comment by iains** [comment]
for the record, stage1 can be very "noisy" with warnings depending on the version of the bootstrap compiler - although folks do check GCC bootstrapped with clang and fix stuff.

99% of the time I am bootstrapping with GCC because I build Ada.

**Comment by ilg-ul** [comment]
> if this is a bootstrap of the home-brew branch

I'm not using homebrew and I don't know what _a bootstrap of the home-brew branch_ is. :-(

In xPack Build Box I have my own bootstrap, which builds `gcc-11.2.0-arm-20211126` (which I guess is very close to your master) with Apple clang, on a macOS 11.6 running on a Mini M1, so the appended logs show a relatively clean build of your branch.

> stage1 can be very "noisy" with warnings depending on the version of the bootstrap compiler

```
 % uname -a
Darwin xbbma.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:38 PDT 2021; root:xnu-7195.141.8~1/RELEASE_ARM64_T8101 arm64
% clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by iains** [comment]
> > if this is a bootstrap of the home-brew branch
> 
> I'm not using homebrew and I don't know what _a bootstrap of the home-brew branch_ is. :-(

Well .. I guess I misunderstood what you'd said about waiting for fixes to be included in homebrew.

> In xPack Build Box I have my own bootstrap, which builds `gcc-11.2.0-arm-20211126` (which I guess is very close to your master) with Apple clang, on a macOS 11.6 running on a Mini M1, so the appended logs show a relatively clean build of your branch.

??? actually, I think we have some confusion here - my branches have nothing to do with Arm's releases - I have no connection with Arm, (I am a freelance developer) I just do work on the Darwin port of GCC in my spare time.

FWIW, 11.2 is quite far from current master (12.0) however, in response to an earlier query from you - I pushed a rebase of back ports form master to 11.2 as 4 branches with the final one containing all the aarch64 stuff:

https://github.com/iains/gcc-11-branch/commits/gcc-11-2-darwin-nov21-apple-si
(on top of rpaths, PCH WIP and necessary backports)

At present, it is not at all clear to me what you are building, so I've no mechanism to determine how to repeat it.

**Comment by iains** [comment]
to be clear:
if you are building gcc-11.2.0-arm-20211126 with clang, then my code is not involved at all.

**Comment by ilg-ul** [comment]
> I misunderstood what you'd said about waiting for fixes to be included in homebrew.
> ??? actually, I think we have some confusion here - my branches have nothing to do with Arm's releases

Sorry for the confusion, I'm using the archives released by @fxcoudert, which generally include your latest commits.

In this case I'm using:

- https://github.com/fxcoudert/gcc/releases/tag/gcc-11.2.0-arm-20211126

The same archives are used in HomeBrew:

- https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb

> if you are building gcc-11.2.0-arm-20211126 with clang, then my code is not involved at all.

Then there must be a misunderstanding somewhere, since I see your commits in that repo:

- <https://github.com/fxcoudert/gcc/commit/4b9a61dab4e59d4ae1c62103e7c4726cdeeda426>

**Comment by iains** [comment]
So, then you are building the homebrew branches ( which FX looks after ); those include some, but not all, of my patches for Darwin.  Please check with homebrew/FX if this is a known problem.

To add to this, at one stage, there was discussion of patching an Arm release and/or a riscv release...

**Comment by fxcoudert** [comment]
Warnings during stage 1 are not considered an issue. You're bootstrapping with clang as system compiler, so this is particularly expected.

**Comment by ilg-ul** [comment]
> you are building the homebrew branches

If that repo is not recommended, then where exactly should I get an up-to-date 11.x source tree to be used as my base compiler for my development environment?

>  there was discussion of patching an Arm release and/or a riscv release...

Yes, these are different projects.

I am currently rebuilding the development environment (XBB), which is based on a 11.2, and should run on 

- macOS 11.6 Arm
- macOS 10.13 Intel

With this development environment I have to build multiple binary packages, including:

- a native standalone GCC 11.2
- a cross arm-none-eabi-gcc 10.3 (based on Arm sources, plus patches)
- a cross riscv-none-embed-gcc 10.2 (based on SiFive sources, plus patches)

**Comment by ilg-ul** [comment]
> Warnings during stage 1 are not considered an issue.

Ok, in this case you can close the ticket.

**Comment by fxcoudert** [comment]
@ilg-ul to sum up the state of things: all of @iains's valuable time (as the expert on gcc/darwin) goes to making a “bleeding edge” version of the port for aarch64-apple-darwin, and getting it integrated into GCC master. This is, by definition, experimental.

I try to help, with my limited knowledge, by creating a relatively “stable” branch against 11.2.0, based on @iains's work, for Homebrew users (and more widely, as other distributors use my branch). But being more stable also means that it has some unfixed bugs, which may have been fixed in @iains's branch in the meantime. So if you find issues, please test on his master branch before reporting to him. I don't want to add to his already great burden in this endeavour!

**Comment by ilg-ul** [comment]
> a relatively “stable” branch against 11.2.0 ...  for Homebrew users (and more widely, as other distributors use my branch)

I think that both my development environment and the cross-platform standalone xPack GCC may benefit from your branch too, at least until 11.3 is released.

> if you find issues, please test on his master branch before reporting to him

To avoid confusions, can you confirm exactly which repo and what branch are you referring to? This one or `iains/gcc-11-branch`? 

I don't want to add to his burden either, I'm just trying to help you two improve GCC, and indirectly help myself have a better development environment.

**Comment by iains** [comment]
> > if you find issues, please test on his master branch before reporting to him

and FAOD I do, of course, want bugs to be reported...
> 
> To avoid confusions, can you confirm exactly which repo and what branch are you referring to? This one or `iains/gcc-11-branch`?

The master for the GCC aarch64 development is here : 
https://github.com/iains/gcc-darwin-arm64

It is rebased approximately weekly onto the latest GCC master and has the latest fixed and proposed code to be upstreamed.

(when rebasing  - I push a copy of the previous branch as -on-xxxxxxxx which is the upstream master revision it is based on - the test results are also related back to that revision - so one can compare with X86 results from the same)

**Comment by fxcoudert** [comment]
> The master for the GCC aarch64 development is here: https://github.com/iains/gcc-darwin-arm64

@ilg-ul all reported bugs should be checked against that branch

**Comment by ilg-ul** [comment]
>  all reported bugs should be checked against that branch

Ok, for the future I'll try to build it too, but for now I only have the HomeBrew branch functional.

**Comment by iains** [comment]
i think this can be closed, we clarified that an amount of warning noise is expected on a stage1 build with a different compiler.  The bootstrap continues with -Werror by default so that warnings on stage2 and 3 would stop the build.
