### ISSUE TITLE
varargs test failure (gcc.c-torture/execute/va-arg-24.c)

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#60]
I've reduced that failure:

```
meau /tmp/irun $ cat toto.c 
#include <stdarg.h>
#include <stdio.h>

static void varargs9 (int q0, int q1, int q2, int q3, int q4, int q5, int q6, int q7, int q8, int q9, ...)
{
  va_list ap;
  int i; 

  __builtin_va_start(ap, q9);
  i = __builtin_va_arg(ap, int);
  printf("%d\n", i);
  __builtin_va_end(ap);
}

int main(void)
{
  varargs9 (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
}
meau /tmp/irun $ ./bin/gcc toto.c && ./a.out
-345473023
```

The code should output 10.

**Comment by fxcoudert** [comment]
I think this may also be the source of the failure for `gfortran.dg/c_kind_params.f90`.

**Comment by iains** [comment]
thanks, we have a posted patch for issue #4 
- so I think to handle this issue once I've managed to integrate the "proper" fix (this is the second case where we are running with a known hack).

**Comment by fxcoudert** [comment]
OK I thought that you had integrated that into the tree. Sorry.
