### ISSUE TITLE
Value range propagation

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#63]
Several of the failing C testcases are about value range propagation (if I understand correctly). I don't see how this could be target-dependent, but clearly it is. This is a typical example:

```
$ cat pr79223.c
/* PR middle-end/79223 - missing -Wstringop-overflow on a memmove overflow
   { dg-do compile }
   { dg-additional-options "-O2 -Wall -Wno-array-bounds -std=gnu99" }  */

typedef __SIZE_TYPE__ size_t;
extern void* memcpy (void*, const void*, size_t);

char d[3];
char s[4];

size_t range (void) { return 4; }

void test_memcpy (void)
{
  memcpy (d, s, range ());   /* { dg-warning ".memcpy. writing 4 or more bytes into a region of size 3 overflows the destination" } */
}
$ ./bin/gcc -O2 -Wall -Wno-array-bounds -std=gnu99 pr79223.c -c -fdump-tree-optimized
```

This should output a warning, and it does on x86_64-apple-darwin and, according to testresults mailing list, on aarch64-gnu-linux.

**Comment by iains** [comment]
in this specific case, comparing x86-64 and aarch64 (today's build)
 x86_64 is expanding the builtin into inline code
 aarch64 is calling range() and then building a call to the library fn.

so, we're probably not going through the pathway that sees a '4' sized array being copied into a '3' sized destination.

**Comment by iains** [comment]
right so somehow aarch64-darwin is not seeing the return value from rang() as being a constant 4:

x86_64: (tree.optimized)
;; Function test_memcpy (test_memcpy, funcdef_no=1, decl_uid=1964, cgraph_uid=2, symbol_order=3)

void test_memcpy ()
{
  <bb 2> [local count: 1073741824]:
  memcpy (&d, &s, 4); [tail call]
  return;

}

---

aarch64: (tree.optimized)
;; Function test_memcpy (test_memcpy, funcdef_no=1, decl_uid=3609, cgraph_uid=2, symbol_order=3)

void test_memcpy ()
{
  long unsigned int _1;

  <bb 2> [local count: 1073741824]:
  _1 = range ();
  memcpy (&d, &s, _1); [tail call]
  return;

**Comment by fxcoudert** [comment]
I'm thinking this one may be the same issue, because it's not seeing that it's calling itself recursively:

```
$ cat gcc.dg/Winfinite-recursion-2.c 
/* { dg-do compile }
   { dg-options "-O2 -Wall -Winfinite-recursion" } */

static int fi_v (void);

int warn_call_fi_v (void)
{
  return fi_v ();             // { dg-message "recursive call" }
}

static int fi_v (void)        // { dg-warning "-Winfinite-recursion" }
{
  return warn_call_fi_v ();
}
$ /tmp/irun/bin/gcc -O2 -Wall -Winfinite-recursion gcc.dg/Winfinite-recursion-2.c -c
```

**Comment by iains** [comment]
your section example lead me to what I think the real issue is - Darwin binds locally for PIC code - without which most things seem non-inlinable and therefore can't be analysed as such..

should be fixed by https://github.com/iains/gcc-darwin-arm64/commit/e62a114bb389e4b32d9eb1f7c01c8cdf0f9f07b4

**Comment by fxcoudert** [comment]
I'll do a regtest without/with that commit, and report.

**Comment by iains** [comment]
I did the without (posted on the test results issue) - the "with" case is running now - but it is a good idea to compare results for stability.. [I did check that it fixed the pr79223 case for a cross-compile].

**Comment by iains** [comment]
before  | after

               === libgomp Summary ===                                                                                         
# of expected passes            11736  |  # of expected passes            11747

                === g++ Summary ===                                                                                             
# of expected passes            213389 |  # of expected passes            213479

                === gcc Summary ===                                                                                             
# of expected passes            150038 |  # of expected passes            150184

                === gfortran Summary ===                                                                                        
# of expected passes            64149 |  # of expected passes            64153

                === jit Summary ===                                                                                             
# of expected passes            7512 |  # of expected passes            7528

... seems like a useful progression.

**Comment by fxcoudert** [comment]
Quite impressive!

- g++ failures down from 171 to 81
- gcc failures down from 459 to 320
- gfortran down from 13 to 11

A couple of regressions:

```
+FAIL: g++.dg/ipa/pr67056.C   scan-ipa-dump cp "Speculative outer type:struct CompositeClass"
+FAIL: gcc.dg/debug/dwarf2/inline5.c scan-assembler-times DW_TAG_lexical_block\\\\)[^#/!@;\\\\|]*[#/!@;\\\\|]+ +[^#/!@\\\\|]*\\\\(DIE \\\\(0x[0-9a-f]*\\\\) DW_TAG_variable 1
+FAIL: gcc.dg/graphite/scop-19.c scan-tree-dump-times graphite "number of SCoPs: 0" 1
+FAIL: gfortran.dg/unlimited_polymorphic_3.f03  -B/private/tmp/ibin/aarch64-apple-darwin21.2.0/./libatomic/  -B/private/tmp/ibin/aarch64-apple-darwin21.2.0/./libatomic/.libs  -Os  execution test
```

plus some timed-out tests. I'll continue to investigate, reduce and report.

**Comment by iains** [comment]
on the regressions, it is probably worth seeing if those are also fails on other Darwin platforms [I think the change is needed for correctness].

However, on X86 I had to clobber some additional registers (on calls) that macOS can use when doing a lazy symbol resolution (we might need something similar here - having said that, I doubt that there are any testsuite cases that would trigger this effect)

**Comment by iains** [comment]
On x86_64 darwin21:
FAIL: g++.dg/ipa/pr67056.C   scan-ipa-dump cp "Speculative outer type:struct CompositeClass"
**
FAIL: gcc.dg/graphite/scop-19.c scan-tree-dump-times graphite "number of SCoPs: 0" 1
FAIL: gfortran.dg/unlimited_polymorphic_3.f03   -Os  execution test

** inline5 also fails the same way on powerpc-darwin9
