### ISSUE TITLE
Target triplet unspecified leads to build failure

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#7]
Obviously a very minor issue, but configuring for a no-bootstrap build on a native box without specifying any of build, host or target, leads to a build failure with:

```
*** Configuration arm-apple-darwin20.0.0 not supported
make[2]: *** [configure-stage1-gcc] Error 1
make[1]: *** [stage1-bubble] Error 2
```

**Comment by iains** [comment]
ah, I only copied config.sub () across from the latest upstream, presumably, I need to add config.guess too (did you try that?)

**Comment by iains** [comment]
should be fixed by
https://github.com/iains/gcc-darwin-arm64/commit/537803028f623d1fdb9f9422fbfe143cef77cd45

**Comment by fxcoudert** [comment]
Confirmed fixed
