### ISSUE TITLE
Fix or silence some more tests

### ISSUE THREAD

**Issue by fxcoudert** [iains/gcc-darwin-arm64#71]
I have a patch at https://gist.github.com/fxcoudert/c7ecb9bacba736e8bdd7d07023f565f3
Can't really create a PR now, my branch is all messed up.

What is does:
- introduce a support function to skip `-mabi=ilp32` tests
- fix some long double vs. _Float128 differences
- disable some big-endian-only tests
- fix one char vs. unsigned char issue
- fix some assembly scans to match darwin expectations

Should fix 14 failures of the current 143 gcc failures.

**Comment by fxcoudert** [comment]
From

```
# of expected passes		150013
# of unexpected failures	143
# of unexpected successes	9
# of expected failures		1239
# of unresolved testcases	8
# of unsupported tests		3519
```

to

```
# of expected passes		150022
# of unexpected failures	126
# of unexpected successes	9
# of expected failures		1239
# of unresolved testcases	5
# of unsupported tests		3526
```

**Comment by iains** [comment]
thanks - I will apply it shortly.

we will need a source-build.texi entry for the new target support (but that is not urgent).

In one of the other fixes, I had to add -fno-signed-char to get the test to work properly, but (IMO) if the test requires unsigned chars, then it is reasonable to expect that to be specific.

**Comment by fxcoudert** [comment]
Updated patch, three more: https://gist.github.com/fxcoudert/b39d81a388d5ea99d4102d5748a7406e

**Comment by iains** [comment]
pushed
