### ISSUE TITLE
__chkstk_darwin linker error

### ISSUE THREAD

**Issue by crazypill** [iains/gcc-darwin-arm64#78]
I'm compiling WSJT-X for Apple M1 and I get a link error related to this function.  I'm not sure where this function should live.  I just stubbed the function and moved on but thought I would report it.  

Thanks again for the great work on gfortran/gcc.
alex

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/aarch64-apple-darwin21/12.0.0/lto-wrapper
Target: aarch64-apple-darwin21
Configured with: ../configure --build=aarch64-apple-darwin21 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-10 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-system-zlib --disable-multilib --with-native-system-header-dir=/usr/include --disable-darwin-at-rpath --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.0.0 20211225 (experimental) (GCC) 
```

**Comment by fxcoudert** [comment]
> I get a link error related to this function

Can you please paste the exact linker command? Otherwise we won't be able to debug this.

`___chkstk_darwin` is emitted by Apple's clang when compiling with `-fstack-check`, which has become the default in recent versions. It lives in system libraries and should always be linked in. But, it has three `_`, not two.

As far as I am away, GCC does not emit such calls.

```
$ cat u.c 
#include <fcntl.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

typedef struct {
    char  d[16];
    void *e;
    struct { char b[5536]; } f;
} i;

void g(void) {
    struct addrinfo hints, *k;
    memset(&hints, 0, sizeof hints);
    getaddrinfo(NULL, NULL, &hints, &k);
}

int main(void) {
    puts("Hello world");
    fflush(stdout);
    close(open("/dev/null", O_RDONLY));
    i context;
    context.e = open;
    printf("%p\n", context.d);
    g();
    return 0;
}
$ clang u.c && nm a.out     
                 U ___chkstk_darwin
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stdoutp
0000000100000000 T __mh_execute_header
                 U _close
                 U _fflush
0000000100003e28 T _g
                 U _getaddrinfo
0000000100003e68 T _main
                 U _memset
                 U _open
                 U _printf
                 U _puts
$ clang u.c -fno-stack-check && nm a.out
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stdoutp
0000000100000000 T __mh_execute_header
                 U _close
                 U _fflush
0000000100003e38 T _g
                 U _getaddrinfo
0000000100003e78 T _main
                 U _memset
                 U _open
                 U _printf
                 U _puts
$ gcc u.c -fstack-check && nm a.out 
                 U ___stdoutp
0000000100000000 T __mh_execute_header
                 U _close
                 U _fflush
0000000100003e40 T _g
                 U _getaddrinfo
0000000100003e88 T _main
                 U _open
                 U _printf
                 U _puts
```

**Comment by crazypill** [comment]
Thank you for getting back to me so quickly.

Please forgive me as I’m not exactly sure how to get the exact linker command.
I looked at the Makefile to get the compile options and did some googling:

gcc -### -o wsprd.c -I/usr/include -Wall -Wno-missing-braces -Wno-unused-result -O3 -ffast-math -L/usr/lib -lfftw3f -lm -lgfortran
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" "-demangle" "-lto_library" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib" "-dynamic" "-arch" "arm64" "-platform_version" "macos" "12.0.0" "12.0" "-syslibroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" "-o" "wsprd.c" "-L/usr/lib" "-L/usr/local/lib" "-lfftw3f" "-lm" "-lgfortran" "-lSystem" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.osx.a”

The problem for me is that I cannot run this make file by itself without error, it seems to be dependent on another make file upstream in order to properly compile.  So I just tried using gcc -### on the individual file to get the link command based on what the makefile says.

Also you are correct in that the missing symbol has three underbars, however when I stubbed the function I only used two as you get one for free being a C function and all.

Hopefully the above has information you can actually use-  if not, please feel free to let me know how to get exactly what you need.  I’m not a gcc expert by any means and I appreciate your patience with me.


nm /Users/alex/wsjtx-debug/wsjtx-prefix/src/wsjtx-build/CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o
0000000000000008 C _PLAN1
0000000000000008 C _PLAN2
0000000000000008 C _PLAN3
                 U ___chkstk_darwin
                 U ___sincos_stret
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stderrp
                 U ___strcpy_chk
                 U ___strncat_chk
                 U _access
                 U _bzero
                 U _calloc
                 U _clock
[snip]

alex

**Comment by iains** [comment]
>  gcc -### -o wsprd.c -I/usr/include -Wall -Wno-missing-braces -Wno-unused-result -O3 -ffast-math -L/usr/lib -lfftw3f -lm -lgfortran Apple clang version 13.0.0 (clang-1300.0.29.3) Target: arm64-apple-darwin21.2.0 Thread model: posix 

0/

The way to get the failing command line is often to run the make [sometimes with V=1 or VERBOSE=1 depending on how the makefile is written] and then redirecting the output to a file - hopefully allowing one to get the exact command that failed.

0.1 For the record, macOS never needs "-lm" the math library is already in libSystem - libm.dylib is just a symlink to libSystem - but putting '-lm' does alter the order in which libraries are presented to link (because it causes libSystem to be presented early instead of last).  We'd need to isolate the exact command line that's failing in order to pin down if this was an effect.

1/
Despite that you are saying "gcc", this is invoking clang (in gcc-4.2.1 compatibility mode) - this is because Xcode intercepts 'gcc' and does this.

 * The issue with (1) is that clang will link with the runtimes *it* uses - not the ones that GCC uses .. so you might need to append GCC's runtimes.  Having said that, it appears that the missing symbol is on that would have been compiled in by clang (but we kinda need more detail to figure out what's happening).

2/
gfortran will work ok without intercepting (as the link driver too).

**Comment by crazypill** [comment]
Thank you for showing me how to capture the build output, here it is:

[ 80%] Building C object CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DBIGSYM=1 -DBOOST_ALL_DYN_LINK -DCMAKE_BUILD -DQT5 -DUNIX -I/Users/alex/wsjtx-debug/wsjtx-prefix/src/wsjtx-build -I/Users/alex/wsjtx-debug/wsjtx-prefix/src/wsjtx -I/opt/homebrew/include -Wall -Wextra -pthread -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.12 -fvisibility=hidden  -include wsjtx_config.h -MD -MT CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o -MF CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o.d -o CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o -c /Users/alex/wsjtx-debug/wsjtx-prefix/src/wsjtx/lib/wsprd/wsprd.c
[ 80%] Linking Fortran executable wsprd
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/wsprd.dir/link.txt --verbose=1
/opt/homebrew/bin/gfortran  -mmacosx-version-min=10.12 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -O3 -DNDEBUG -O3 -fbounds-check -funroll-all-loops -fno-f2c -ffpe-summary=invalid,zero,overflow,underflow -Wall -Wno-conversion -fno-second-underscore -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.12 CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o CMakeFiles/wsprd.dir/lib/wsprd/wsprsim_utils.c.o CMakeFiles/wsprd.dir/lib/wsprd/wsprd_utils.c.o CMakeFiles/wsprd.dir/lib/wsprd/fano.c.o CMakeFiles/wsprd.dir/lib/wsprd/jelinek.c.o CMakeFiles/wsprd.dir/lib/wsprd/tab.c.o CMakeFiles/wsprd.dir/lib/wsprd/nhash.c.o CMakeFiles/wsprd.dir/lib/init_random_seed.c.o CMakeFiles/wsprd.dir/lib/indexx.f90.o CMakeFiles/wsprd.dir/lib/wsprd/osdwspr.f90.o -o wsprd  /opt/homebrew/lib/libfftw3f_threads.dylib /opt/homebrew/lib/libfftw3f.dylib 
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/wsprsim_utils.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/wsprd_utils.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/fano.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/jelinek.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/tab.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/osdwspr.f90.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/init_random_seed.c.o) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (CMakeFiles/wsprd.dir/lib/indexx.f90.o) was built for newer macOS version (11.0) than being linked (10.12)ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/nhash.c.o) was built for newer macOS version (11.0) than being linked (10.12)

ld: warning: dylib (/opt/homebrew/lib/libfftw3f_threads.dylib) was built for newer macOS version (11.3) than being linked (10.12)
ld: warning: dylib (/opt/homebrew/lib/libfftw3f.dylib) was built for newer macOS version (11.3) than being linked (10.12)
ld: warning: dylib (/usr/local/lib/libgfortran.dylib) was built for newer macOS version (12.1) than being linked (10.12)
ld: warning: dylib (/usr/local/lib/libquadmath.dylib) was built for newer macOS version (12.1) than being linked (10.12)
Undefined symbols for architecture arm64:
  "___chkstk_darwin", referenced from:
      _sync_and_demodulate in wsprd.c.o
      _noncoherent_sequence_detection in wsprd.c.o
      _subtract_signal2 in wsprd.c.o
      _main in wsprd.c.o
      _get_wspr_channel_symbols in wsprsim_utils.c.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status

**Comment by iains** [comment]
>/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.12 ...

> /opt/homebrew/lib/libfftw3f_threads.dylib /opt/homebrew/lib/libfftw3f.dylib ld: warning: object file (CMakeFiles/wsprd.dir/lib/wsprd/wsprd.c.o) was built for newer macOS version (11.0) than being linked (10.12) 

There are several instances of this and you have -mmacosx-version-min=10.12 on the link line.

There was no Arm64 10.12 macOS (not even sure if there was arm64 iPhoneOS that far back)  .. so you are pointing the build at an SDK without aarch64/arm64 slices in the libraries....

> arm64: "___chkstk_darwin", referenced from: _sync_and_demodulate in wsprd.c.o _noncoherent_sequence_detection in wsprd.c.o _subtract_signal2 in wsprd.c.o _main in wsprd.c.o _get_wspr_channel_symbols in wsprsim_utils.c.o ld: symbol(s) not found for architecture arm64 collect2: error: ld returned 1 exit status
> […](#)

.. try fixing the build to target -mmacosx-version-min=11.0

**Comment by crazypill** [comment]
Thank you, that makes perfect sense.  It also fixes the link warning.
alex
