### ISSUE TITLE
GCC 12.1

### ISSUE THREAD

**Issue by ilg-ul** [iains/gcc-darwin-arm64#92]
I just gave GCC 12.1 a try. It passed on Intel, but failed on M1:

```console
checking if mkdir takes one argument... no
*** Configuration aarch64-apple-darwin20.6.0 not supported
make[1]: *** [Makefile:4555: configure-gcc] Error 1
make[1]: Leaving directory '/Users/ilg/Work/gcc-12.1.0-1/darwin-arm64/build/gcc-12.1.0'
make: *** [Makefile:1031: all] Error 2
ilg@cloud ~ % 
```

Any thoughts?

**Comment by iains** [comment]
you would need to use the 12.1-darwin-release-0 branch:
https://github.com/iains/gcc-12-branch/releases/tag/gcc-12.1-darwin-r0
aarch64 darwin supports is not yet upstreamed, so only available here.

**Comment by ilg-ul** [comment]
> aarch64 darwin supports is not yet upstreamed

For the record, I just finished building the cross RISC-V toolchain based on 12.1, so host support for AArch64 Darwin is already there (actually not a big deal); only the target part is not yet upstreamed.

**Comment by iains** [comment]
> > aarch64 darwin supports is not yet upstreamed
> 
> For the record, I just finished building the cross RISC-V toolchain based on 12.1, so host support for AArch64 Darwin is already there (actually not a big deal); only the target part is not yet upstreamed.

That's correct - although the target part is ≈ 100x the size of the host support.

NOTE : Host support is only available on the 'darwin' branch for 11.x (since adding that is not a 'regression fix').

**Comment by ilg-ul** [comment]
> NOTE : Host support is only available on the 'darwin' branch for 11.x (since adding that is not a 'regression fix').

And I guess the same will be true for the target part in 12.x, so 13.x might be the next chance to include it.

**Comment by iains** [comment]
> > NOTE : Host support is only available on the 'darwin' branch for 11.x (since adding that is not a 'regression fix').
> 
> And I guess the same will be true for the target part in 12.x, so 13.x might be the next chance to include it.

Upstream, yes that's right (hopefully, there will be enough time this cycle, all depends on $dayjob);
 
The 12.x darwin branch version will be maintained to keep track of any fixes made to the master/upstream version.

**Comment by ilg-ul** [comment]
@fxcoudert, do you have any updates for this? 

I saw there was some work on building GCC 12 on Homebrew, including merging the fix in CMake issue [23500](https://gitlab.kitware.com/cmake/cmake/-/issues/23500), and there is a separate [gcc@12.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc@12.rb), but the public [gcc.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb) still points to 11.3.

Do you expect more work on 12.1 for Homebrew, or I can already use your patch?

**Comment by ilg-ul** [comment]
I compiled 12.1 in my build environment, with the patch used in `gcc@12.rb`, and it passed. :-)

But if it is not final, I can postpone my release.

**Comment by iains** [comment]
https://github.com/iains/gcc-12-branch/releases/tag/gcc-12.1-darwin-r1

Please put GCC 12 issues here:
https://github.com/iains/gcc-12-branch/issues

**Comment by ilg-ul** [comment]
@fxcoudert, any changes in gcc-12.1-darwin-r1 worth an update of gcc@12.rb?

**Comment by fxcoudert** [comment]
@ilg-ul it is being done in https://github.com/Homebrew/homebrew-core/pull/103713

**Comment by ilg-ul** [comment]
Great, thank you!

**Comment by ilg-ul** [comment]
The xPack GCC 12.1.0-1 binaries are also available:

- <https://github.com/xpack-dev-tools/gcc-xpack/releases/tag/v12.1.0-1>
